[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "package_file_generator"
version = "0.0.1"
authors = [
    { name = "Iñaki Pujol", email = "ipujol10@gmail.com" }
]
description = "Generate the files to make a package out of a piece of code"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ipujol10/generatePythonPackage"
"Bug Tracker" = "https://github.com/ipujol10/generatePythonPackage/issues"
